name: 📦 New component or update
description: Suggest an new component or update
title: "[Component or Update]: "
labels: ["component", "triage"]
body:
  - type: textarea
    id: code-implementation
    attributes:
      label: Is the component implemented in code?
      description: If it does, please add the links to the documentation page for all existing implementations.
      placeholder: Link to relevant pages
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Describe the use case
      description: What will this component / update be used for? Is it already used?
      placeholder: Describe the use case
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions you've considered.
      placeholder: What have you considered as alternatives?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: Anything that can be of help?
    validations:
      required: false
  - type: textarea
    id: contribution
    attributes:
      label: Have you built this in figma already or would you like to?
      description: If you have build the component please add a figma link.
      placeholder: We love contributions. If you did not build it yet, we can work through it together.
    validations:
      required: true
