name: 🐛 Bug Report
description: Submit a bug report if you found something wrong
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What is not working as expected?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: checkboxes
    id: latestRelease
    attributes:
      label: Are you using the [latest release](https://github.com/primer/figma/releases)?
      description: You can verify this by opening the lib view (`option` + `cmd` + `o`) and checking the `Updates` tab
      options:
        - label: I am using the latest version of `Primer Web` and `Primer Primitives: Light`
          required: false
  - type: markdown
    attributes:
      value: <!-- Attach any screenshots or videos that may help understand the issue -->
