name: Issue assignment

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: "Auto-assign issue"
        uses: pozil/auto-assign-issue@v1
        with:
          teams: primer/figma-reviewers
          numOfAssignee: 1
          allowSelfAssign: false
