name: Docgen Primer Brand

on:
  workflow_dispatch:

jobs:
  generate-components-json:
    name: Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm i

      - name: Generate component documentation JSON
        run: npm run docgen:web

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update packages/web/generated/components.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIGMA_API_TOKEN: ${{ secrets.FIGMA_API_TOKEN }}
